export { fragments as AcfBlendCallout } from './BlendCallout.fragments';
export { fragments as AcfBlogPosts } from './BlogPosts.fragments';
export { fragments as AcfCannabinoidCallout } from './CannabinoidCallout.fragments';
export { fragments as AcfCategoryTabs } from './CategoryTabs.fragments';
export { fragments as AcfCollectionCardsSet } from './CollectionCardsSet.fragments';
export { fragments as AcfCollectionLinks } from './CollectionLinks.fragments';
export { fragments as AcfCollectionSlider } from './CollectionSlider.fragments';
export { fragments as AcfDiscountCodeBar } from './DiscountCodeBar.fragments';
export { fragments as AcfFaq } from './Faq.fragments';
export { fragments as AcfFeaturedCollection } from './FeaturedCollection.fragments';
export { fragments as AcfHeroSection } from './HeroSection.fragments';
export { fragments as AcfHeroSlider } from './HeroSlider.fragments';
export { fragments as AcfHighlightsGroup } from './HighlightsGroup.fragments';
export { fragments as AcfImageCarousel } from './ImageCarousel.fragments';
export { fragments as AcfImageSlider } from './ImageSlider.fragments';
export { fragments as AcfLoyaltyTiers } from './LoyaltyTiers.fragments';
export { fragments as AcfPromoSlider } from './PromoSlider.fragments';
export { fragments as AcfQuizHero } from './QuizHero.fragments';
export { fragments as AcfResponsiveImage } from './ResponsiveImage.fragments';
export { fragments as AcfReviewsCarousel } from './ReviewsCarousel.fragments';
export { fragments as AcfSaleCountdownHero } from './SaleCountdownHero.fragments';
export { fragments as AcfShopByMood } from './ShopByMood.fragments';
export { fragments as AcfShoppableHero } from './ShoppableHero.fragments';
export { fragments as AcfSocialProofStrip } from './SocialProofStrip.fragments';
export { fragments as AcfUgcCarousel } from './UgcCarousel.fragments';
export { fragments as AcfValuePropsSet } from './ValuePropsSet.fragments';
export { fragments as AcfWhatSetsUsApart } from './WhatSetsUsApart.fragments';

import { CoreBlocks } from '@faustwp/blocks';
export const CoreImage = (CoreBlocks as any).CoreImage?.fragments;
export const CoreParagraph = (CoreBlocks as any).CoreParagraph?.fragments;
